### ISSUE TITLE
Исправление багов и ошибок программы

### ISSUE THREAD

**Issue by 2DeaR** [trpo2023/cw-ip-214_password-generator#14]

**Comment by 2DeaR** [comment]
Исправил .gitignore, избавился от глобальной переменной. Андрей исправил CI и Makefile

**Comment by 2DeaR** [comment]
Внесли изменения в ряд функций и избавились от утечек памяти

**Comment by VitalyMart** [comment]
Исправил баг и добавил тесты, теперь вывод не осуществляется в функциях для создания паролей.

**Comment by 2DeaR** [comment]
Оптимизация main.c, вынесли в отдельные функции генерацию пароля и ввод данных пользователем
